apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmy-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-argocd
  template:
    metadata:
      labels:
        app: my-argocd
    spec:
      containers:
        - name: argocd
          image: tushar04072000/web-app:01
          ports:
            - containerPort: 3000 # React default port
          # Add resource requests/limits if needed
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
