apiVersion: v1
kind: Service
metadata:
  name: my-argocd-service
spec:
  selector:
    app: my-argocd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort # Use NodePort for Minikube
